name: Do update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Parse sheet
      run: |
        pipenv run SHEETS_KEY=${{ secrets.SHEETS_KEY }} python main.py
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - uses: peter-evans/create-pull-request@v5-rc
      with:
        add-paths: |
          server/dailyrun.log
          server/hryGlyphics.json
          server/rosetta.json
        branch: sheet-data-${{ steps.date.outputs.date }}
        base: main
        title: Sheet data ${{ steps.date.outputs.date }}
        commit-message: Sheet data ${{ steps.date.outputs.date }}
        reviewers: probablyHelmis
        delete-branch: true
    - name: Display output PR
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number}}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-number}}"
